version: "3.9"

services:
  db:
    container_name: noc_v2_db
    image: postgres
    volumes:
      - noc_v2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=noc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  noc_v2: